In [38]:
import pandas as pd
import re
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import nltk

### Load Data

In [6]:
data = pd.read_csv("tripadvisor-hotel-reviews.csv")

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  109 non-null    object
 1   Rating  109 non-null    int64
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

In [8]:
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [10]:
data['Review'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews did valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe just noisy neighbors, aveda bath products nice, did not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience having pay 40 parking night,  '

In [11]:
data['review_lowercase'] = data['Review'].str.lower()

In [12]:
data.head()

                                              Review  ...                                   review_lowercase
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 3 columns]

### Stop word removal

In [13]:
en_stopwords = stopwords.words('english')
print(en_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [14]:
en_stopwords.remove('not')

In [16]:
data['review_no_stopwords'] = data['review_lowercase'].apply(lambda x: ' '.join([word for word in x.split() if word not in en_stopwords]))

In [17]:
data.head()

                                              Review  ...                                review_no_stopwords
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 4 columns]

In [18]:
data['review_no_stopwords'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe noisy neighbors, aveda bath products nice, not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience pay 40 parking night,'

### Punctuation
We want to remove punctation but we notice we have a few reviews with the symbol * instead of the word star. We want to keep this as it might add meaning to the review. We can do this using what we learned about regular expressions.

In [19]:
data["review_no_stopwords_no_punct"] = data.apply(lambda x: re.sub("r[*]", "start", x['review_no_stopwords']), axis = 1)

In [20]:
data.head()

                                              Review  ...                       review_no_stopwords_no_punct
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4* experience hotel monaco seat...
3  unique, great stay, wonderful time hotel monac...  ...  unique, great stay, wonderful time hotel monac...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay, went seahawk game aweso...

[5 rows x 5 columns]

In [21]:
data["review_no_stopwords_no_punct"] = data.apply(lambda x: re.sub(r"([^\w\s])", "", x['review_no_stopwords_no_punct']) , axis = 1)

In [22]:
data.head()

                                              Review  ...                       review_no_stopwords_no_punct
0  nice hotel expensive parking got good deal sta...  ...  nice hotel expensive parking got good deal sta...
1  ok nothing special charge diamond member hilto...  ...  ok nothing special charge diamond member hilto...
2  nice rooms not 4* experience hotel monaco seat...  ...  nice rooms not 4 experience hotel monaco seatt...
3  unique, great stay, wonderful time hotel monac...  ...  unique great stay wonderful time hotel monaco ...
4  great stay great stay, went seahawk game aweso...  ...  great stay great stay went seahawk game awesom...

[5 rows x 5 columns]

### Tokenizing

In [24]:
data['tokenized'] = data.apply(lambda x: word_tokenize(x['review_no_stopwords_no_punct']) ,axis = 1)

In [25]:
data.head()

                                              Review  ...                                          tokenized
0  nice hotel expensive parking got good deal sta...  ...  [nice, hotel, expensive, parking, got, good, d...
1  ok nothing special charge diamond member hilto...  ...  [ok, nothing, special, charge, diamond, member...
2  nice rooms not 4* experience hotel monaco seat...  ...  [nice, rooms, not, 4, experience, hotel, monac...
3  unique, great stay, wonderful time hotel monac...  ...  [unique, great, stay, wonderful, time, hotel, ...
4  great stay great stay, went seahawk game aweso...  ...  [great, stay, great, stay, went, seahawk, game...

[5 rows x 6 columns]

In [26]:
data['tokenized'][0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'reviews',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillows',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bangs',
 'doors',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbors',
 'aveda',
 'bath',
 'products',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

### Stemming

In [27]:
ps = PorterStemmer()

In [28]:
data["stemmed"] = data["tokenized"].apply(lambda tokens: [ps.stem(word) for word in tokens])

In [29]:
data.head()

                                              Review  ...                                            stemmed
0  nice hotel expensive parking got good deal sta...  ...  [nice, hotel, expens, park, got, good, deal, s...
1  ok nothing special charge diamond member hilto...  ...  [ok, noth, special, charg, diamond, member, hi...
2  nice rooms not 4* experience hotel monaco seat...  ...  [nice, room, not, 4, experi, hotel, monaco, se...
3  unique, great stay, wonderful time hotel monac...  ...  [uniqu, great, stay, wonder, time, hotel, mona...
4  great stay great stay, went seahawk game aweso...  ...  [great, stay, great, stay, went, seahawk, game...

[5 rows x 7 columns]

In [30]:
data['stemmed'][0]

['nice',
 'hotel',
 'expens',
 'park',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversari',
 'arriv',
 'late',
 'even',
 'took',
 'advic',
 'previou',
 'review',
 'valet',
 'park',
 'check',
 'quick',
 'easi',
 'littl',
 'disappoint',
 'nonexist',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfort',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillow',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morn',
 'loud',
 'bang',
 'door',
 'open',
 'close',
 'hear',
 'peopl',
 'talk',
 'hallway',
 'mayb',
 'noisi',
 'neighbor',
 'aveda',
 'bath',
 'product',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantag',
 'stay',
 'longer',
 'locat',
 'great',
 'walk',
 'distanc',
 'shop',
 'overal',
 'nice',
 'experi',
 'pay',
 '40',
 'park',
 'night']

### Lemmatization

In [31]:
lemmatizer = WordNetLemmatizer()

In [32]:
data["lemmatized"] = data["tokenized"] \
                    .apply(lambda tokens: \
                    [lemmatizer.lemmatize(token) \
                     for token in tokens])

In [33]:
data['lemmatized'][0]

['nice',
 'hotel',
 'expensive',
 'parking',
 'got',
 'good',
 'deal',
 'stay',
 'hotel',
 'anniversary',
 'arrived',
 'late',
 'evening',
 'took',
 'advice',
 'previous',
 'review',
 'valet',
 'parking',
 'check',
 'quick',
 'easy',
 'little',
 'disappointed',
 'nonexistent',
 'view',
 'room',
 'room',
 'clean',
 'nice',
 'size',
 'bed',
 'comfortable',
 'woke',
 'stiff',
 'neck',
 'high',
 'pillow',
 'not',
 'soundproof',
 'like',
 'heard',
 'music',
 'room',
 'night',
 'morning',
 'loud',
 'bang',
 'door',
 'opening',
 'closing',
 'hear',
 'people',
 'talking',
 'hallway',
 'maybe',
 'noisy',
 'neighbor',
 'aveda',
 'bath',
 'product',
 'nice',
 'not',
 'goldfish',
 'stay',
 'nice',
 'touch',
 'taken',
 'advantage',
 'staying',
 'longer',
 'location',
 'great',
 'walking',
 'distance',
 'shopping',
 'overall',
 'nice',
 'experience',
 'pay',
 '40',
 'parking',
 'night']

In [34]:
data.head()

                                              Review  ...                                         lemmatized
0  nice hotel expensive parking got good deal sta...  ...  [nice, hotel, expensive, parking, got, good, d...
1  ok nothing special charge diamond member hilto...  ...  [ok, nothing, special, charge, diamond, member...
2  nice rooms not 4* experience hotel monaco seat...  ...  [nice, room, not, 4, experience, hotel, monaco...
3  unique, great stay, wonderful time hotel monac...  ...  [unique, great, stay, wonderful, time, hotel, ...
4  great stay great stay, went seahawk game aweso...  ...  [great, stay, great, stay, went, seahawk, game...

[5 rows x 8 columns]

In [35]:
tokens_clean = sum(data['lemmatized'], [])

In [39]:
# unigrams: n=1
unigrams = (pd.Series \
            (nltk.ngrams(tokens_clean, 1)) \
            .value_counts()) 
print(unigrams)

(hotel,)        292
(room,)         275
(great,)        126
(not,)          122
(stay,)          95
               ...
(absolute,)       1
(mayflower,)      1
(30the,)          1
(scarce,)         1
(connected,)      1
Name: count, Length: 2588, dtype: int64

In [40]:
# bigrams: n=2
bigrams = (pd.Series \
           (nltk.ngrams(tokens_clean, 2)) \
           .value_counts()) 
print(bigrams)

(great, location)     24
(space, needle)       21
(hotel, monaco)       16
(great, view)         12
(staff, friendly)     12
                      ..
(like, guest)          1
(didnt, make)          1
(personnel, didnt)     1
(minute, stay)         1
(food, raffle)         1
Name: count, Length: 8262, dtype: int64

In [41]:
ngrams_4 = (pd.Series \
            (nltk.ngrams(tokens_clean, 4)) \
            .value_counts()) 
print(ngrams_4)

(high, floor, great, view)                   2
(definitely, stay, crowne, plaza)            2
(needle, experience, music, project)         2
(nice, hotel, husband, stayed)               2
(really, comfortable, clean, location)       2
                                            ..
(unfortunately, warwick, seattle, hotel)     1
(warwick, seattle, hotel, dissapointment)    1
(seattle, hotel, dissapointment, trip)       1
(hotel, dissapointment, trip, 3)             1
(raffle, hotel, right, street)               1
Name: count, Length: 9387, dtype: int64